mandb
echo "MAN DB COMMAND EXECUTED SUCCESSFULLY"
mandb
echo "MAN DB COMMAND EXECUTED SUCCESSFULLY"
manb
echo "MAN DB COMMAND EXECUTED SUCCESSFULLY"
updatedb
echo "UPDATEDB COMMAD EXECUTED SUCCESSFULLY"
mandb
echo "MAN DB COMMAND EXECUTED SUCCESSFULLY"
updatedb
echo "UPDATEDB COMMAD EXECUTED SUCCESSFULLY"
updatedb
echo "UPDATEDB COMMAD EXECUTED SUCCESSFULLY"
banner UPDATED_DB
mandb
echo "MAN DB COMMAND EXECUTED SUCCESSFULLY"
banner MANDB_UPDATED
banner text
banner 123456789
yum update -y
yum upgrade -y

